### ISSUE TITLE
GPL compatibility status

### ISSUE THREAD

**Issue by Hamcha** [me-shaon/GLWTPL#6]
Could you please clarify in the README if this license is GPL compatible or not?

**Comment by kirillDanshin** [comment]
@Hamcha GPL is a copyleft license and it doesn't allow any sublicensing. so - no, there is no license that is compatible with GPL, even different GPL versions are incompatible with each other due to denied sublicensing. There is only one way to make GPL-licensed product compatible with other GPL version: make product "multi-licensed": include both licenses. that will allow users to choose one of the versions.

This comment is also licensed under GLWTPL. (lol)
GLWT Public License
Copyright (c) 2018-present Kirill Danshin

**Comment by kirillDanshin** [comment]
@me-shaon this issue may be closed

**Comment by GigabyteProductions** [comment]
I would imagine the original question was probably regarding the linking issue with GPL. In which case, it might be desirable to use GLWTPL code in a GPL-licensed project, for example.

Similar can already be done with Apache License 2.0 (among other licenses).

Understanding this, I believe what needs to be answered to clarify this is if the anti-attribution term counts as an "additional restriction" or conflicts with any other term of GPL. I would think not, because it's not exactly a restriction on "use".

See: https://www.apache.org/licenses/GPL-compatibility.html
See: https://web.archive.org/web/20180607013611/https://www.apache.org/licenses/GPL-compatibility.html

See: https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses
See: https://web.archive.org/web/20180607013623/https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses

See: https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean
See: https://web.archive.org/web/20180607013805/https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean

**Comment by me-shaon** [comment]
@kirillDanshin Your comment can't be GLWTPL licensed as you left a trace of you in the copyright note.

**Comment by kirillDanshin** [comment]
@me-shaon that comment was licensed under GLWTPL v1, https://github.com/me-shaon/GLWTPL/commit/662bdfaef4ed093f1e192f8a7b1cda822c08dd19#diff-9879d6db96fd29134fc802214163b95aR1, that was latest at the time
